### PR TITLE
Moving Commands and Exceptions from q2q.py

### PR DESCRIPTION
**Pull request by chellygel**

### CODE REVIEW

**Comment by glyph** [comment]
poke

**Comment by chellygel** [comment]
Sorry, I havent poked this in a week! I am having trouble figuring out these errors. After a good sleep, i'm going to take a look at this!

**Comment by glyph** [comment]
poke

**Comment by glyph** [comment]
In case @chellygel doesn't have time (which I suspect is likely!) I feel like I should note that if the commit at the tip of this PR is present in the master branch the PR will automatically close :)

**Pull request merged**
