### PR TITLE
Txscrypt password

### LINKED ISSUE #34: Passwords are encoded in hex, change this to Txscrypt
Currently we dont do fun things with passwords, we should do this correctly using txscrypt.

https://pypi.python.org/pypi/txscrypt/3.0.0

### PR DESCRIPTION
**Pull request by markrwilliams**
Closes #34.

`txscrypt` runs scrypt in a thread, so the dictionary-like user storage mechanism won't do.  This PR introduces a new interface to replace it: `IQ2QUserStore`.  Its `store` method returns a `Deferred` that fires only when the key has been computed.
 
Verification happens through `UserShadowPassword`, a new `IUsernamePassword` implementer whose `checkPassword` calls out to `txscrypt`.  Unfortunately the logic is backwards because `checkPassword` is called with the stored key derived by `txscrypt.computeKey`.

[A bug in `Q2QService.requestCertificateForAddress` has been fixed](https://github.com/twisted/vertex/commit/2aee9f32b663d0ba8f18e49a967501e024f1dfa9).

I wrote some standardized fakes using `pretend` which is not my preference.  I didn't want to add yet another testing strategy in this commit, though.

### CODE REVIEW

**Comment by markrwilliams** [comment]
Gonna try and kick codecov by closing and reopening.

**Comment by markrwilliams** [comment]
Coverage wasn't able to resolve the vertex paths into the site-packages folder, so it complained that it couldn't collect any data.  I put in a [dumb hack](https://github.com/twisted/vertex/pull/46/commits/10cb0a178415e2f0dab1f12be6b72a0e45407c4c#diff-354f30a63fb0907d4ad57269548329e3R17) so that the `vertex` in site-packages was the `vertex` as in the current working directory.

A better solution would be to use `.coveragerc` to make the paths equivalent.  An even better solution would be to use tox and `changedir` so that the only `vertex` is the one that got installed.  We could even use a `src/` directory for that, too.

In the interim, though, this will make codecov report stuff.

**Comment by glyph** [comment]
Everything about this is great (except the aforementioned dumb hack) so I am going to land it, not least of which because it is a totally critical security problem if anyone were to use Vertex today.

**Comment by glyph** [comment]
One other bit of feedback - can you make an upstream issue for txscrypt for testing, please?  The stubs should really move to the same project that houses the code.

**Comment by mithrandi** [comment]
Relevant to this PR, I guess: I've started[1] a new project over at https://github.com/mithrandi/txpasslib which I hope Vertex can eventually use instead of txscrypt.

[1] Set up CI but haven't actually written any code yet.

**Comment by glyph** [comment]
Thanks for the heads up @mithrandi !

**Pull request merged**
