### PR TITLE
reimplement state machine using automat - work in progress

### PR DESCRIPTION
**Pull request by glyph**

### CODE REVIEW

**Comment by glyph** [comment]
State machine, as visualized by automat:

state-machine

**Comment by glyph** [comment]
Another take (graphviz is weird, and, I think, non-deterministic):

take2

**Comment by ashfall** [comment]
This is exciting

**Comment by glyph** [comment]
@ashfall - thank you for saying so. Can I count on you for a code review? :)

**Comment by ashfall** [comment]
I'll likely give you a :shipit: in my excitement, but sure! :)

**Comment by glyph** [comment]
> I'll likely give you a :shipit:  in my excitement, but sure! :)

The alternative will be me just YOLOing it up onto master, vertex does not have enough active developers to have mandatory code review any more :)

**Comment by glyph** [comment]
It needs a lot more docstrings and such, but so does the rest of vertex; this is a huge improvement so I'm just going ahead with it.

**Pull request merged**
